// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package sqlc

import (
	"time"
)

type Paper struct {
	ArxivID  string    `json:"arxiv_id"`
	Title    string    `json:"title"`
	Abstract string    `json:"abstract"`
	Authors  string    `json:"authors"`
	Date     time.Time `json:"date"`
}

type SavedPaper struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	PaperID   string    `json:"paper_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}
