// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: papers.sql

package sqlc

import (
	"context"
	"time"
)

const createPaper = `-- name: CreatePaper :one
INSERT INTO papers (
    arxiv_id,
    title,
    abstract,
    authors,
    date
) VALUES ($1, $2, $3, $4, $5
) RETURNING arxiv_id, title, abstract, authors, date
`

type CreatePaperParams struct {
	ArxivID  string    `json:"arxiv_id"`
	Title    string    `json:"title"`
	Abstract string    `json:"abstract"`
	Authors  string    `json:"authors"`
	Date     time.Time `json:"date"`
}

func (q *Queries) CreatePaper(ctx context.Context, arg CreatePaperParams) (Paper, error) {
	row := q.db.QueryRowContext(ctx, createPaper,
		arg.ArxivID,
		arg.Title,
		arg.Abstract,
		arg.Authors,
		arg.Date,
	)
	var i Paper
	err := row.Scan(
		&i.ArxivID,
		&i.Title,
		&i.Abstract,
		&i.Authors,
		&i.Date,
	)
	return i, err
}

const deletePaper = `-- name: DeletePaper :exec
DELETE FROM papers
WHERE arxiv_id = $1
`

func (q *Queries) DeletePaper(ctx context.Context, arxivID string) error {
	_, err := q.db.ExecContext(ctx, deletePaper, arxivID)
	return err
}

const deleteSavedPaper = `-- name: DeleteSavedPaper :exec
DELETE from saved_papers
WHERE user_id = $1 AND paper_id = $2
`

type DeleteSavedPaperParams struct {
	UserID  int64  `json:"user_id"`
	PaperID string `json:"paper_id"`
}

func (q *Queries) DeleteSavedPaper(ctx context.Context, arg DeleteSavedPaperParams) error {
	_, err := q.db.ExecContext(ctx, deleteSavedPaper, arg.UserID, arg.PaperID)
	return err
}

const getPaper = `-- name: GetPaper :one
SELECT arxiv_id, title, abstract, authors, date FROM papers
WHERE arxiv_id = $1
LIMIT 1
`

func (q *Queries) GetPaper(ctx context.Context, arxivID string) (Paper, error) {
	row := q.db.QueryRowContext(ctx, getPaper, arxivID)
	var i Paper
	err := row.Scan(
		&i.ArxivID,
		&i.Title,
		&i.Abstract,
		&i.Authors,
		&i.Date,
	)
	return i, err
}

const getPapers = `-- name: GetPapers :many
SELECT arxiv_id, title, abstract, authors, date FROM papers
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetPapersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPapers(ctx context.Context, arg GetPapersParams) ([]Paper, error) {
	rows, err := q.db.QueryContext(ctx, getPapers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Paper{}
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.ArxivID,
			&i.Title,
			&i.Abstract,
			&i.Authors,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedPaperIDs = `-- name: GetSavedPaperIDs :many
SELECT p.paper_id
FROM saved_papers AS p
WHERE user_id = $1
ORDER BY p.created_at
`

func (q *Queries) GetSavedPaperIDs(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSavedPaperIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var paper_id string
		if err := rows.Scan(&paper_id); err != nil {
			return nil, err
		}
		items = append(items, paper_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePaperForUser = `-- name: SavePaperForUser :one
INSERT INTO saved_papers(
     user_id,
     paper_id
) VALUES ($1, $2
) RETURNING id, user_id, paper_id, created_at
`

type SavePaperForUserParams struct {
	UserID  int64  `json:"user_id"`
	PaperID string `json:"paper_id"`
}

func (q *Queries) SavePaperForUser(ctx context.Context, arg SavePaperForUserParams) (SavedPaper, error) {
	row := q.db.QueryRowContext(ctx, savePaperForUser, arg.UserID, arg.PaperID)
	var i SavedPaper
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaperID,
		&i.CreatedAt,
	)
	return i, err
}
